name: yachtOne
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.9.9+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  align_positioned: ^2.0.1
  amplitude_flutter: ^3.1.0
  animated_text_kit: ^4.2.1
  app_tracking_transparency: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  back_button_interceptor: ^5.0.0
  blobs: ^1.2.0
  bubble: ^1.1.9+1
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0-nullsafety.0
  charts_flutter: ^0.10.0
  circular_check_box: ^1.0.4
  cloud_firestore: ^2.5.3
  cloud_functions: ^3.0.4
  confetti: ^0.6.0-nullsafety
  countup: ^0.1.3
  cupertino_icons: ^1.0.3
  data_connection_checker: ^0.3.4
  expandable_page_view: ^1.0.6
  firebase_analytics: ^8.3.1
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  firebase_in_app_messaging: ^0.5.0+10
  firebase_messaging: ^10.0.8
  firebase_remote_config: ^0.11.0+1
  firebase_storage: ^10.0.4
  flare_flutter: ^3.0.0
  flutter_cache_manager: ^3.0.2
  flutter_chat_bubble: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_screenutil: ^5.0.0+2
  flutter_segment: ^3.0.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^9.0.0
  get: ^4.3.8
  get_it: ^6.1.1
  get_storage:
  google_mobile_ads: ^0.13.4
  http: ^0.13.3
  image_picker: ^0.8.3
  intl: ^0.17.0
  kakao_flutter_sdk: ^0.8.1
  like_button: ^2.0.2
  lite_rolling_switch: ^0.1.1
  mixpanel_flutter: ^1.2.1
  ntp: ^2.0.0
  package_info: ^2.0.0
  path: ^1.7.0
  path_provider: ^2.0.1
  preload_page_view: ^0.1.4
  provider: ^5.0.0
  quiver: ^3.0.1
  random_string: ^2.2.0-nullsafety
  rive: ^0.7.28
  rflutter_alert: ^2.0.2
  rxdart: ^0.27.0
  shared_preferences: ^2.0.5
  stacked: ^2.1.6
  syncfusion_flutter_charts: ^19.3.43
  timezone: ^0.7.0
  toggle_switch: ^0.1.8
  tutorial_coach_mark: ^1.1.1
  showcaseview: ^1.1.1
  universal_io: ^2.0.4
  url_launcher: ^6.0.9
  vibration: ^1.7.4-nullsafety.0
  flutter_native_splash:
  flutter_inappwebview: ^5.3.2
  pull_to_refresh: ^2.0.0
  introduction_screen: ^2.1.0
  sign_in_with_apple: ^3.2.0
  flutter_linkify: ^5.0.2
  render_metrics: ^2.0.1
  styled_widget: ^0.3.1+2
  email_validator: ^2.0.1
  paginate_firestore: ^1.0.2
  dotted_border: ^2.0.0+1
  firebase_app_check: ^0.0.2+2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/yacht_app_logo.png"

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#798AE6"
  # background_image: "assets/images/background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file.
  image: assets/logos/white_splash.png

  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  #fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

  # To enable support for Android 12, set the following parameter to true.  Defaults to false.
  #android12: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/secLogo/
    - assets/documents/
    - assets/buttons/
    - assets/icons/
    - assets/icons/bottom_navigation/
    - assets/illusts/
    - assets/illusts/quest/
    - assets/illusts/not_exists/
    - assets/illusts/onboarding/
    - assets/logos/
    - assets/badges/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # - family: PostNoBills
    #   fonts:
    #     - asset: assets/fonts/postnobillscolombo-semibold.ttf
    # - family: NanumHandWriting
    #   fonts:
    #     - asset: assets/fonts/nanum_handwriting_goding.ttf
    # - family: AdventPro
    #   fonts:
    #     - asset: assets/fonts/advent_pro/AdventPro-Regular.ttf
    # - family: Arkhip
    #   fonts:
    #     - asset: assets/fonts/arkhip_regular.ttf

    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Regular.otf
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Thin.otf
          weight: 200
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Black.otf
          weight: 900

    - family: Default
      fonts:
        - asset: assets/fonts/s-core/SCDream4.otf

    - family: SCore
      fonts:
        # - asset: assets/fonts/s-core/SCDream4.otf
        - asset: assets/fonts/s-core/SCDream1.otf
          weight: 100
        - asset: assets/fonts/s-core/SCDream2.otf
          weight: 200
        - asset: assets/fonts/s-core/SCDream3.otf
          weight: 300
        - asset: assets/fonts/s-core/SCDream4.otf
          weight: 400
        - asset: assets/fonts/s-core/SCDream5.otf
          weight: 500
        - asset: assets/fonts/s-core/SCDream6.otf
          weight: 600
        - asset: assets/fonts/s-core/SCDream7.otf
          weight: 700
        - asset: assets/fonts/s-core/SCDream8.otf
          weight: 800
        - asset: assets/fonts/s-core/SCDream9.otf
          weight: 900
    - family: DmSans
      fonts:
        - asset: assets/fonts/dm_sans/DMSans-Regular.ttf
        - asset: assets/fonts/dm_sans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/dm_sans/DMSans-Bold.ttf
          weight: 700
    - family: AppleSDGothicNeo
      fonts:
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoR.otf
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoUL.otf
          weight: 100
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoT.otf
          weight: 200
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoL.otf
          weight: 300
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoM.otf
          weight: 500
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoSB.otf
          weight: 600
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoB.otf
          weight: 700
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoEB.otf
          weight: 800
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoH.otf
          weight: 900
        # - asset: assets/fonts/advent_pro/AdventPro-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
