name: yachtOne
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+34

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  align_positioned: ^1.2.8
  amplitude_flutter: ^2.2.2
  app_tracking_transparency: ^2.0.0
  apple_sign_in: ^0.1.0
  auto_size_text: ^2.1.0
  back_button_interceptor: ^4.4.0
  blobs: ^1.2.0
  bubble: ^1.1.9+1
  cached_network_image: ^2.3.1
  carousel_slider: ^3.0.0
  charts_flutter: ^0.9.0
  circular_check_box: ^1.0.4
  cloud_firestore: ^0.14.1+3
  cloud_functions: ^0.6.0+1
  confetti: ^0.5.4+1
  countup: ^0.1.3
  cupertino_icons: ^0.1.3
  data_connection_checker: ^0.3.4
  firebase_admob: ^0.10.2
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0+1
  firebase_in_app_messaging: ^0.2.0+3
  firebase_messaging: ^7.0.3
  firebase_remote_config: ^0.4.2
  firebase_storage: ^4.0.0
  flare_flutter: ^2.0.6
  flutter_cache_manager: ^2.1.2
  flutter_chat_bubble: ^1.0.2
  flutter_launcher_icons: ^0.9.0
  flutter_screenutil: ^3.1.1
  flutter_svg: ^0.20.0-nullsafety.3
  fluttertoast: ^7.1.1
  font_awesome_flutter: ^8.11.0
  flare_checkbox: ^1.0.4
  get: ^3.23.1
  get_it: ^4.0.2
  google_mobile_ads: ^0.13.0
  http: ^0.12.2
  intl: ^0.16.1
  kakao_flutter_sdk: ^0.5.2
  like_button: ^1.0.3
  ntp: ^1.0.7
  package_info: ^0.4.3+2
  path: ^1.7.0
  path_provider: ^1.6.1
  preload_page_view: ^0.1.4
  provider: ^4.1.2
  random_string: ^2.1.0
  rflutter_alert: ^1.0.3
  rxdart: ^0.24.1
  shared_preferences: ^0.5.10
  stacked: ^1.7.6
  syncfusion_flutter_charts: ^18.3.42
  timezone: ^0.6.1
  toggle_switch: ^0.1.8
  tutorial_coach_mark: ^0.5.2
  url_launcher: ^5.7.10
  vibration: ^1.7.1
  sliding_switch: ^0.0.3
  lite_rolling_switch: ^0.1.1
  flutter_native_admob: ^2.1.0+3
  webview_flutter: ^1.0.7
  mixpanel_flutter: ^1.0.0
  flutter_segment: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ggook_app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/secLogo/
    - assets/documents/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # - family: PostNoBills
    #   fonts:
    #     - asset: assets/fonts/postnobillscolombo-semibold.ttf
    - family: NanumHandWriting
      fonts:
        - asset: assets/fonts/nanum_handwriting_goding.ttf
    - family: AdventPro
      fonts:
        - asset: assets/fonts/advent_pro/AdventPro-Regular.ttf
    - family: Arkhip
      fonts:
        - asset: assets/fonts/arkhip_regular.ttf
    - family: DmSans
      fonts:
        - asset: assets/fonts/dm_sans/DMSans-Regular.ttf
        - asset: assets/fonts/dm_sans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/dm_sans/DMSans-Bold.ttf
          weight: 700
    - family: AppleSDL
      fonts:
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoL.ttf
    - family: AppleSDM
      fonts:
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoM.ttf
    - family: AppleSDB
      fonts:
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoB.ttf
    - family: AppleSDEB
      fonts:
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoEB.ttf
    - family: AppleSDH
      fonts:
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoH.ttf
        # - asset: assets/fonts/advent_pro/AdventPro-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
