name: yachtOne
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+34

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  align_positioned: ^2.0.1
  amplitude_flutter: ^3.1.0
  app_tracking_transparency: ^2.0.0
  apple_sign_in: ^0.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  back_button_interceptor: ^5.0.0
  blobs: ^1.2.0
  bubble: ^1.1.9+1
  google_mobile_ads: ^0.13.0
  cached_network_image: ^3.1.0-alpha.1
  carousel_slider: ^4.0.0-nullsafety.0
  charts_flutter: ^0.10.0
  circular_check_box: ^1.0.4
  cloud_firestore: ^2.2.0
  cloud_functions: ^1.1.0
  confetti: ^0.6.0-nullsafety
  countup: ^0.1.3
  cupertino_icons: ^1.0.3
  data_connection_checker: ^0.3.4
  firebase_analytics: ^8.1.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_in_app_messaging: ^0.5.0+4
  firebase_messaging: ^10.0.0
  firebase_remote_config: ^0.10.0-dev.4
  firebase_storage: ^8.1.0
  flare_flutter: ^3.0.0
  flutter_cache_manager: ^3.0.2
  flutter_chat_bubble: ^1.0.2
  flutter_launcher_icons: ^0.9.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^9.0.0
  get: ^4.1.4
  get_it: ^6.1.1
  http: ^0.13.3
  intl: ^0.17.0
  kakao_flutter_sdk: ^0.6.3
  like_button: ^2.0.2
  ntp: ^2.0.0
  package_info: ^2.0.0
  path: ^1.7.0
  path_provider: ^2.0.1
  preload_page_view: ^0.1.4
  provider: ^5.0.0
  random_string: ^2.2.0-nullsafety
  rflutter_alert: ^2.0.2
  rxdart: ^0.27.0
  shared_preferences: ^2.0.5
  stacked: ^2.1.6
  syncfusion_flutter_charts: ^19.1.64
  timezone: ^0.7.0
  toggle_switch: ^0.1.8
  tutorial_coach_mark: ^1.0.0
  url_launcher: ^6.0.4
  vibration: ^1.7.4-nullsafety.0
  lite_rolling_switch: ^0.1.1
  # flutter_native_admob: ^2.1.0+3
  webview_flutter: ^2.0.7
  mixpanel_flutter: ^1.0.0
  flutter_segment: ^3.0.0
  universal_io: ^2.0.4
  quiver: ^3.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ggook_app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/secLogo/
    - assets/documents/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # - family: PostNoBills
    #   fonts:
    #     - asset: assets/fonts/postnobillscolombo-semibold.ttf
    - family: NanumHandWriting
      fonts:
        - asset: assets/fonts/nanum_handwriting_goding.ttf
    - family: AdventPro
      fonts:
        - asset: assets/fonts/advent_pro/AdventPro-Regular.ttf
    - family: Arkhip
      fonts:
        - asset: assets/fonts/arkhip_regular.ttf
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Regular.otf
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Thin.otf
          weight: 200
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Black.otf
          weight: 900
    - family: DmSans
      fonts:
        - asset: assets/fonts/dm_sans/DMSans-Regular.ttf
        - asset: assets/fonts/dm_sans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/dm_sans/DMSans-Bold.ttf
          weight: 700
    - family: AppleSDGothicNeo
      fonts:
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoR.otf
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoUL.otf
          weight: 100
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoT.otf
          weight: 200
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoL.otf
          weight: 300
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoM.otf
          weight: 500
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoSB.otf
          weight: 600
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoB.otf
          weight: 700
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoEB.otf
          weight: 800
        - asset: assets/fonts/apple_sd_gothic_neo/AppleSDGothicNeoH.otf
          weight: 900
        # - asset: assets/fonts/advent_pro/AdventPro-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
